# This is a basic workflow to help you get started with Actions

name: Deployment

# # Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: 
      name: staging
      url: https://dinopass.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Show environment key
        run: echo Hello, ${{ secrets.ENVIRONMENT_KEY }}

      - run: 'echo "$ENVIRONMENT_KEY" > key && tail key'
        shell: bash
        env:
          ENVIRONMENT_KEY: ${{secrets.ENVIRONMENT_KEY}}

  deploy_production:
    environment: 
      name: production
      url: https://cheese.com

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get date
        run: date ${{ secrets.DATE_FORMAT }}

      # Runs a single command using the runners shell
      - name: Get Time
        run: date ${{ secrets.DATE_TIME_ONLY }}

  send_notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: always()
    needs:
      - deploy_staging
      - deploy_production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send notice
        run: echo success
