# This is a basic workflow to help you get started with Actions

name: Environment Deploy

# # Controls when the workflow will run
on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: staging

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Show environment key
        run: echo Hello, ${{ secrets.ENVIRONMENT_KEY }}
